module XCB
  CW_EVENT_MASK = 2048

  EVENT_MASK_NO_EVENT = 0
  EVENT_MASK_KEY_PRESS = 1
  EVENT_MASK_KEY_RELEASE = 2
  EVENT_MASK_BUTTON_PRESS = 4
  EVENT_MASK_BUTTON_RELEASE = 8
  EVENT_MASK_ENTER_WINDOW = 16
  EVENT_MASK_LEAVE_WINDOW = 32
  EVENT_MASK_POINTER_MOTION = 64
  EVENT_MASK_POINTER_MOTION_HINT = 128
  EVENT_MASK_BUTTON_1_MOTION = 256
  EVENT_MASK_BUTTON_2_MOTION = 512
  EVENT_MASK_BUTTON_3_MOTION = 1024
  EVENT_MASK_BUTTON_4_MOTION = 2048
  EVENT_MASK_BUTTON_5_MOTION = 4096
  EVENT_MASK_BUTTON_MOTION = 8192
  EVENT_MASK_KEYMAP_STATE = 16384
  EVENT_MASK_EXPOSURE = 32768
  EVENT_MASK_VISIBILITY_CHANGE = 65536
  EVENT_MASK_STRUCTURE_NOTIFY = 131072
  EVENT_MASK_RESIZE_REDIRECT = 262144
  EVENT_MASK_SUBSTRUCTURE_NOTIFY = 524288
  EVENT_MASK_SUBSTRUCTURE_REDIRECT = 1048576
  EVENT_MASK_FOCUS_CHANGE = 2097152
  EVENT_MASK_PROPERTY_CHANGE = 4194304
  EVENT_MASK_COLOR_MAP_CHANGE = 8388608
  EVENT_MASK_OWNER_GRAB_BUTTON = 16777216

  MOD_MASK_SHIFT = 1
  MOD_MASK_LOCK = 2
  MOD_MASK_CONTROL = 4
  MOD_MASK_1 = 8
  MOD_MASK_2 = 16
  MOD_MASK_3 = 32
  MOD_MASK_4 = 64
  MOD_MASK_5 = 128

  STACK_MODE_ABOVE = 0,
  STACK_MODE_BELOW = 1,
  STACK_MODE_TOP_IF = 2,
  STACK_MODE_BOTTOM_IF = 3,
  STACK_MODE_OPPOSITE = 4

  KEY_PRESS = 2
  KEY_RELEASE = 3
  BUTTON_PRESS = 4
  BUTTON_RELEASE = 5
  MOTION_NOTIFY = 6
  ENTER_NOTIFY = 7
  MAP_REQUEST = 20
  CONFIGURE_NOTIFY = 22
  CONFIGURE_REQUEST = 23
  PROPERTY_NOTIFY = 28

  CONFIG_WINDOW_X = 1
  CONFIG_WINDOW_Y = 2
  CONFIG_WINDOW_WIDTH = 4
  CONFIG_WINDOW_HEIGHT = 8
  CONFIG_WINDOW_BORDER_WIDTH = 16
  CONFIG_WINDOW_SIBLING = 32
  CONFIG_WINDOW_STACK_MODE = 64

  GRAB_MODE_SYNC = 0
  GRAB_MODE_ASYNC = 1

  LEFT_MOUSE = 1
  MIDDLE_MOUSE = 2
  RIGHT_MOUSE = 3

  NONE = 0
  CURRENT_TIME = 0
  WINDOW_NONE = 0

  INPUT_FOCUS_NONE = 0
  INPUT_FOCUS_POINTER_ROOT = 1
end
